---
version: '3'
services:
  zipkin:
    image: openzipkin/zipkin
    networks:
      - microservices-network
    container_name: zipkin
    ports:
      - "9411:9411"

  mysql:
    image: mysql:latest
    networks:
      - microservices-network
    container_name: JMT_SQL_Container
    environment:
      MYSQL_ROOT_PASSWORD: new_password
      MYSQL_DATABASE: jmt
      MYSQL_USER: admin
      MYSQL_PASSWORD: ADMIN1234
    ports:
      - "3308:3306"
    volumes:
      - ./database_export.sql:/docker-entrypoint-initdb.d/database_export.sql

  postgres:
    image: postgres
    networks:
      - microservices-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: jboss/keycloak
    networks:
      - microservices-network
    container_name: keycloak
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password

  eureka-server:
    image: stitts5401/eureka-server:latest
    pull_policy: always
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin

  api-gateway:
    image: stitts5401/api-gateway:latest
    pull_policy: always
    networks:
      - microservices-network
    container_name: api-gateway
    ports:
      - "8282:8080"
    expose:
      - "8282"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY= TRACE
      - spring_r2dbc_password=Password@123
      - spring_r2dbc_username=ADMIN
    depends_on:
      - zipkin
      - eureka-server

  client-service:
    restart: unless-stopped
    image: stitts5401/client-service:latest
    pull_policy: always
    networks:
      - microservices-network
    container_name: client-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
      - eureka-server
      - keycloak
      - api-gateway

  user-service:
    image: stitts5401/user-service:latest
    pull_policy: always
    networks:
      - microservices-network
    container_name: user-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
      - eureka-server
      - api-gateway

networks:
  microservices-network:
    driver: bridge
volumes:
  postgres_data:
    driver: local