server:
  port: 8761

spring:
  application:
    name: discovery-service
  output:
    ansi:
      enabled: always
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
app:
  eureka:
    username: eureka
    password: password

